/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'wowawesome\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-doble-monitor': '&#xe936;',
		'icon-candado-de-seguridad-cerrado': '&#xe947;',
		'icon-corazon-rayado': '&#xe948;',
		'icon-pantalla-de-monitor': '&#xe949;',
		'icon-refresh': '&#xe94a;',
		'icon-github-d': '&#xe902;',
		'icon-github-g': '&#xe903;',
		'icon-github-x': '&#xe904;',
		'icon-github': '&#xe900;',
		'icon-hhm': '&#xe901;',
		'icon-ico-codepen': '&#xe92a;',
		'icon-ico-codesandbox': '&#xe92f;',
		'icon-ico-replit': '&#xe930;',
		'icon-w3': '&#xe931;',
		'icon-b-google-my-business': '&#xe90b;',
		'icon-b-grindr': '&#xe90a;',
		'icon-b-hornet': '&#xe909;',
		'icon-b-mercado-libre': '&#xe908;',
		'icon-b-onlyfans': '&#xe907;',
		'icon-b-scruff': '&#xe905;',
		'icon-google-my-business': '&#xe90c;',
		'icon-grindr': '&#xe90d;',
		'icon-hornet': '&#xe90e;',
		'icon-mercado-libre': '&#xe914;',
		'icon-onlyfans': '&#xe91b;',
		'icon-scruff': '&#xe91d;',
		'icon-netflix-gayflix': '&#xe929;',
		'icon-tumblr': '&#xe92b;',
		'icon-youtube': '&#xea5c;',
		'icon-tripadvisor': '&#xf65e;',
		'icon-google': '&#xea5b;',
		'icon-whatsapp': '&#xea5a;',
		'icon-facebook-azul-letra': '&#xf0a1;',
		'icon-gmail': '&#xe92c;',
		'icon-tumbrl': '&#xf661;',
		'icon-intagram-camera': '&#xf66c;',
		'icon-pinterest': '&#xe92d;',
		'icon-send': '&#xe92e;',
		'icon-repliit': '&#xf65a;',
		'icon-codesandbox': '&#xf65b;',
		'icon-w3spaces': '&#xf663;',
		'icon-hi5': '&#xf662;',
		'icon-css3': '&#xe934;',
		'icon-gitpod': '&#xe932;',
		'icon-html5': '&#xe933;',
		'icon-medium': '&#xe935;',
		'icon-xiib': '&#xf0b5;',
		'icon-xiiber-circular': '&#xf5c3;',
		'icon-emoji-bien': '&#xe93d;',
		'icon-emoji-molesto': '&#xe93e;',
		'icon-emoji-positivo': '&#xe93f;',
		'icon-dick-vector': '&#xe940;',
		'icon-h': '&#xe906;',
		'icon-logo-viajemos-todxs-por-mexico-turismo-gay-turismo-rosa-color': '&#xf344;',
		'icon-corazones-love': '&#xf509;',
		'icon-pregunta': '&#xf50a;',
		'icon-preguntas': '&#xf50b;',
		'icon-cursor-hand': '&#xf630;',
		'icon-donaciones': '&#xf633;',
		'icon-hospedaje': '&#xf63d;',
		'icon-transporte-en-bus-v2': '&#xf63e;',
		'icon-codepen': '&#xf657;',
		'icon-www': '&#xf65f;',
		'icon-facebook-azul-letra1': '&#xf0a5;',
		'icon-like': '&#xf676;',
		'icon-twiiter-bird': '&#xf675;',
		'icon-twitter-bird': '&#xf5a4;',
		'icon-intagram-camera1': '&#xf66e;',
		'icon-instagram': '&#xee02;',
		'icon-envio-terrestre': '&#xea3b;',
		'icon-enemigos-digitales': '&#xea3c;',
		'icon-escribio-autor': '&#xea3d;',
		'icon-pagoOkey': '&#xea3e;',
		'icon-emoji': '&#xea3f;',
		'icon-frankestein': '&#xea40;',
		'icon-mascarilla-covid': '&#xea41;',
		'icon-avatar-bear': '&#xea42;',
		'icon-avatar-leather': '&#xea43;',
		'icon-underground': '&#xea44;',
		'icon-avatar-hombre-circulo': '&#xea45;',
		'icon-usuario-curculo-negro': '&#xf5a8;',
		'icon-avatar-hombre': '&#xea46;',
		'icon-drag-rupaul': '&#xea47;',
		'icon-regresar': '&#xed14;',
		'icon-l': '&#xea48;',
		'icon-luna-one': '&#xea49;',
		'icon-sol-one': '&#xea4a;',
		'icon-m': '&#xea4b;',
		'icon-pacman': '&#xea4c;',
		'icon-corazon': '&#xea4d;',
		'icon-logo-dragvesti': '&#xf257;',
		'icon-logo-dragvesti-negro': '&#xea4f;',
		'icon-logo-dragvesti-blanco-letras': '&#xea50;',
		'icon-logo-hihello': '&#xea51;',
		'icon-hihello-monster-color-hover': '&#xea53;',
		'icon-xiiber-logo-horizontal-color': '&#xea57;',
		'icon-logo-cgt-mx': '&#xec40;',
		'icon-logo-xiiber-bus-a-tepozspa': '&#xea59;',
		'icon-viajero': '&#xea68;',
		'icon-solicitar-transporte': '&#xf45f;',
		'icon-gato1': '&#xea61;',
		'icon-mota': '&#xf3cf;',
		'icon-yas-queen': '&#xea62;',
		'icon-i-love-fuck': '&#xf0b6;',
		'icon-sexoral-one': '&#xf45b;',
		'icon-bailar': '&#xea63;',
		'icon-avatar-fuera-del-closet': '&#xea64;',
		'icon-hombre': '&#xea66;',
		'icon-pareja-gay': '&#xf40c;',
		'icon-pareja-gay-love': '&#xf40d;',
		'icon-avatar-hombres-gay-icon-sombras-siluetas': '&#xea67;',
		'icon-leather-item': '&#xf0c2;',
		'icon-mascarilla': '&#xf3a6;',
		'icon-corriendo': '&#xf094;',
		'icon-sigue-la-flecha': '&#xf45e;',
		'icon-remando': '&#xf453;',
		'icon-en-bicicleta': '&#xf09b;',
		'icon-renta-de-carros': '&#xf454;',
		'icon-bus-de-lado': '&#xea65;',
		'icon-condon': '&#xf090;',
		'icon-verga-one': '&#xf5a6;',
		'icon-condon-one': '&#xf091;',
		'icon-poppers': '&#xf416;',
		'icon-mundo-one': '&#xf3d1;',
		'icon-pastel': '&#xf40e;',
		'icon-pastel-maanitas': '&#xf410;',
		'icon-rifa': '&#xf457;',
		'icon-rifa-one': '&#xf458;',
		'icon-shot': '&#xf45c;',
		'icon-shot-one': '&#xf45d;',
		'icon-tv': '&#xf56c;',
		'icon-todo-incluido': '&#xf56a;',
		'icon-agregar-negocio': '&#xea69;',
		'icon-flecha-atras': '&#xf0a8;',
		'icon-flecha-siguiente': '&#xf0a9;',
		'icon-etiquetas-codigo': '&#xf09f;',
		'icon-arrow-circle-abajo': '&#xea6a;',
		'icon-arrow-circle-arriba': '&#xea6b;',
		'icon-bus': '&#xea6c;',
		'icon-alerta-del-bus': '&#xea6d;',
		'icon-bus-horario': '&#xea6e;',
		'icon-pastel-entero': '&#xf40f;',
		'icon-pets': '&#xf411;',
		'icon-comida-rapida': '&#xf08f;',
		'icon-restaurante': '&#xf456;',
		'icon-margarita': '&#xf3a5;',
		'icon-playa': '&#xf412;',
		'icon-sombrilla-de-playa': '&#xf460;',
		'icon-ferry': '&#xf0a7;',
		'icon-motorcycle': '&#xf3d0;',
		'icon-pokebola': '&#xf413;',
		'icon-pokemon-mimikyu': '&#xf415;',
		'icon-pokemon-eevee': '&#xf414;',
		'icon-location_pin': '&#xf0c3;',
		'icon-check-list': '&#xeffc;',
		'icon-star': '&#xf461;',
		'icon-star_outline': '&#xf462;',
		'icon-emoji-a-medias': '&#xf098;',
		'icon-emoji-feliz': '&#xf099;',
		'icon-emoji-triste': '&#xf09a;',
		'icon-lavarse-las-manos': '&#xf0c1;',
		'icon-enjabonarse-las-manos': '&#xf09c;',
		'icon-secarse-las-manos': '&#xf45a;',
		'icon-touch_app': '&#xf56b;',
		'icon-configuraciones': '&#xf092;',
		'icon-mapa-de-sitio': '&#xf3a4;',
		'icon-alertas': '&#xea70;',
		'icon-celular-en-mano-tomar-foto': '&#xeb88;',
		'icon-copiar': '&#xf093;',
		'icon-guardar': '&#xf0b2;',
		'icon-faq': '&#xea71;',
		'icon-elipsix': '&#xf097;',
		'icon-error': '&#xf09d;',
		'icon-error_outline': '&#xf09e;',
		'icon-ayuda': '&#xea72;',
		'icon-menu-puntos': '&#xf3ac;',
		'icon-elipsis': '&#xf096;',
		'icon-menu': '&#xf3ab;',
		'icon-carrito-de-compras': '&#xea73;',
		'icon-tarjeta-de-regalo': '&#xf463;',
		'icon-verificado': '&#xf5a7;',
		'icon-reserva-en-lina': '&#xf455;',
		'icon-cancelacion-libre': '&#xea74;',
		'icon-calendario': '&#xea75;',
		'icon-calendario-editar': '&#xea76;',
		'icon-viajes-one': '&#xf5bf;',
		'icon-viajes': '&#xf5be;',
		'icon-wifi': '&#xf5c1;',
		'icon-todas-las-tarjetas': '&#xea77;',
		'icon-entradas': '&#xea78;',
		'icon-boleto-avion': '&#xea79;',
		'icon-gratis': '&#xea7a;',
		'icon-experiencias': '&#xf0a0;',
		'icon-notificaciones': '&#xf3d2;',
		'icon-home-big': '&#xf0b4;',
		'icon-home': '&#xf0b3;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
